# Matemática para Ciencia de los Datos
# Quiz 1

María Auxiliadora Mora
Instituto Tecnológico de Costa Rica, 

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo en jupyter ( .IPYNB ). 

Modo de trabajo: Individual.


---

Objetivo: experimentar con conceptos elementales respecto a matrices para reforzar el conocimiento adquirido en clase usando Python con la librería Pytorch.

Utilice en todos los ejercicios tensores de Pytorch. 

---


**Pregunta 1 (10 puntos, 5 puntos cada ejercicio)**

Considerando que la transpuesta de una matriz es el resultado de cambiar las filas a columnas. Sea una matriz $A\in\mathbb{R}^{m\times n}$, su transpuesta se escribe como $A^{T}\in\mathbb{R}^{n\times m}$ y sus entradas están dadas por: 

\begin{equation}
\left(A^{T}\right)_{i,j}=A_{j,i}.
\end{equation}

Las siguientes son propiedades de la transpuesta: 

- $\left(A^{T}\right)^{T}=A$
- $\left(AB\right)^{T}=B^{T}A^{T}$
- $\left(A+B\right)^{T}=A^{T}+B^{T}$.



---



Utilizando pytorch, genere dos matrices con datos aleatorios de dimensiones $A\in\mathbb{R}^{4\times 3}$   y  $B\in\mathbb{R}^{3\times 4}$  y muestre que las siguientes propiedades se cumplen con las matrices propuestas.

**Pregunta 1.1**

$\left(A^{T}\right)^{T}=A$

**Pregunta 1.2**

$\left(AB\right)^{T}=B^{T}A^{T}$



In [61]:
#---------------------
#Pregunta 1.1: (𝐴𝑇)𝑇=𝐴
#---------------------

# Bibliotecas
import torch as torch
import numpy as np


def testTranspuesta1(A):
    """
    Verifica que la transpuesta de la transpuesta es igual a la matriz inicial.
    Parámetros:
       A: matriz       
    Retorna:
       esIgual: booleano.
    """
    print("Matriz inicial")
    print( A )
    
    print("Transpuesta de matriz inicial")
    T = torch.transpose(A, 0, 1)
    print( T )
    
    print("Transpuesta de Transpuesta")
    T2 = torch.transpose(T, 0, 1)
    print( T2 )
    
    esIgual = torch.equal( A, T2)
    print("¿Igual matriz inicial a su transpuesta-transpuesta?", esIgual)
    return esIgual


torch.manual_seed(0)
  
# Matriz Randon 4x3 
A = torch.randn(size=(4,3))

# Matriz Randon 3x4
B = torch.randn(size=(3,4))


testTranspuesta1(A)
testTranspuesta1(B)
 


Matriz inicial
tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820]])
Transpuesta de matriz inicial
tensor([[ 1.5410,  0.5684,  0.4033, -0.4033],
        [-0.2934, -1.0845,  0.8380, -0.5966],
        [-2.1788, -1.3986, -0.7193,  0.1820]])
Transpuesta de Transpuesta
tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820]])
¿Igual matriz inicial a su transpuesta-transpuesta? True
Matriz inicial
tensor([[-0.8567,  1.1006, -1.0712,  0.1227],
        [-0.5663,  0.3731, -0.8920, -1.5091],
        [ 0.3704,  1.4565,  0.9398,  0.7748]])
Transpuesta de matriz inicial
tensor([[-0.8567, -0.5663,  0.3704],
        [ 1.1006,  0.3731,  1.4565],
        [-1.0712, -0.8920,  0.9398],
        [ 0.1227, -1.5091,  0.7748]])
Transpuesta de Transpuesta
tensor([[-0.8567,  1.1006, -1.0712,  0.1227],
        [-0.5663,  0.3731, -

True

In [63]:
#--------------------------
#Pregunta 1.2: (𝐴𝐵)𝑇=𝐵𝑇𝐴𝑇
#--------------------------

# Bibliotecas
import torch as torch
import numpy as np


def testTranspuesta2(A,B):
    """
    Verifica (𝐴𝐵)𝑇=𝐵𝑇𝐴𝑇
    Parámetros:
       A: matriz       
    Retorna:
       esIgual: booleano.
    """
    
    left = torch.transpose(A.mm(B),0,1) #left side of equation
    print ("Left side: ", left)
    right  = torch.mm(B.transpose(0,1), A.transpose(0,1))  # right side of equation
    print ("Right side: ", right)
    
    esIgual = torch.equal( left, right) #compare both sides
    print("¿Propiedad (𝐴𝐵)𝑇=𝐵𝑇𝐴𝑇 se cumple?", esIgual)
    return esIgual


torch.manual_seed(0)
  
# Matriz Randon 4x3 
A = torch.randn(size=(4,3))


# Matriz Randon 3x4
B = torch.randn(size=(3,4))



testTranspuesta2(A,B)



Left side:  tensor([[-1.9610, -0.3908, -1.0865,  0.7508],
        [-1.5869, -1.8161, -0.2910, -0.4014],
        [-3.4366, -0.9559, -1.8555,  1.1353],
        [-1.0563,  0.6227, -1.7725,  0.9919]])
Right side:  tensor([[-1.9610, -0.3908, -1.0865,  0.7508],
        [-1.5869, -1.8161, -0.2910, -0.4014],
        [-3.4366, -0.9559, -1.8555,  1.1353],
        [-1.0563,  0.6227, -1.7725,  0.9919]])
¿Propiedad (𝐴𝐵)𝑇=𝐵𝑇𝐴𝑇 se cumple? True


True

**Pregunta 2 (10 puntos, 5 puntos cada ejercicio)**


Un conjunto de vectores $\left\{ \vec{x}_{1},\vec{x}_{2},\ldots,\vec{x}_{n}\right\} \in\mathbb{R}^{m}$ se dice que es linealmente independiente, si ningún vector de tal conjunto puede ser representado como una combinación lineal del resto de vectores. De lo contrario, si uno de los vectores en tal conjunto puede ser representado como una combinación lineal del resto de vectores, entonces los vectores son linealmente dependientes, lo que se expresa como: 

\begin{equation}
\vec{x}_{j}=\sum_{i=1}^{n-1}\alpha_{i}\vec{x}_{i}
\end{equation}

para cualquier conjunto de valores escalares $\alpha_{1},\ldots,\alpha_{n-1}\in\mathbb{R}$ se dice que el vector $\vec{x}_{j}\in\mathbb{R}^{m}$ es linealmente dependiente de los vectores $\vec{x}_{i}$. 



---

**Pregunta 2.1**

Proponga una matriz $A\in\mathbb{R}^{5\times 5}$, que no sea la matriz identidad, de manera que dicha matriz sea de rango completo. Muestre con pytorch que cumple esta propiedad.

**Pregunta 2.2**
Ahora hágale cambios a su matriz de manera que sea de rango $3$, y luego más cambios para que sea de rango $2$. Muestre cómo va cambiando la matriz y el cálculo del rango en pytorch.

In [4]:
#-------------------------------------------
#Pregunta 2.1: Matriz 5x5 de rango completo
#-------------------------------------------

# Bibliotecas
import torch as torch

A = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [0 , 2. , 2., 0 , 0 ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [0 , 1. , 0, 4. ,0 ],
                   [1. , 0 , 2., 0 , 6. ]])

print("================================")
print("Matriz 5x5 de rango completo")
print(A)
print("Rango de la matriz (rango completo) ", torch.linalg.matrix_rank(A))

Matriz 5x5 de rango completo
Matriz A
tensor([[1., 2., 3., 4., 5.],
        [0., 2., 2., 0., 0.],
        [1., 0., 3., 0., 0.],
        [0., 1., 0., 4., 0.],
        [1., 0., 2., 0., 6.]])
rango de la matriz  tensor(5)


In [64]:
#--------------------------------------------------
#Pregunta 2.2: Transformar la matriz en rango 3 y 2
#--------------------------------------------------

# Bibliotecas
import torch as torch

A = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [2. , 4. , 6., 8. , 10. ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [3. , 0 , 9., 0 ,0 ],
                   [1. , 0 , 2., 0 , 6. ]])

print("================================")
print("Matriz 5x5 de rango 3")
print(A)
print("Rango de la matriz = ", torch.linalg.matrix_rank(A))

B = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [2. , 4. , 6., 8. , 10. ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [3. , 0 , 9., 0 ,0 ],
                   [2. , 0 , 6., 0 , 0 ]])

print("================================")
print("Matriz 5x5 de rango 2")
print(B)
print("Rango de la matriz = ", torch.linalg.matrix_rank(B))

Matriz 5x5 de rango 3
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 2.,  4.,  6.,  8., 10.],
        [ 1.,  0.,  3.,  0.,  0.],
        [ 3.,  0.,  9.,  0.,  0.],
        [ 1.,  0.,  2.,  0.,  6.]])
Rango de la matriz =  tensor(3)
Matriz 5x5 de rango 2
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 2.,  4.,  6.,  8., 10.],
        [ 1.,  0.,  3.,  0.,  0.],
        [ 3.,  0.,  9.,  0.,  0.],
        [ 2.,  0.,  6.,  0.,  0.]])
Rango de la matriz =  tensor(2)


**Pregunta 3 (5 puntos)**

Pseudo inversa de una matriz. Sean las siguientes propiedades:

1. $ \left(A^{T}A\right)^{-1}A^{T}\approx A^{+} $
2.  $\left(A^{T}A\right)^{+}A^{T}=A^{+}$

Seleccione alguna de las propiedades anteriores, cree una función que reciba una matriz y demuestre que se cumple la propiedad seleccionada. 

Pruebe su función con una matriz invertible y con una no invertible. 

In [67]:
#---------------------------------------
#Pregunta 3.1: La propiedad (𝐴𝑇𝐴)+𝐴𝑇=𝐴+
#---------------------------------------

# Bibliotecas
import torch as torch

def testPInversaPropiedad2(A):
    """
    Verifica si se cumple la propiedad (𝐴𝑇𝐴)+𝐴𝑇=𝐴+
    Parámetros:
       A: matriz      
    Retorna:
       esIgual: booleano.
    """
    print("Matriz inicial")
    print( A )
    
    try:
      A.inverse()
      print("Éxito en la inversa")
    except:
      print("Falló la inversa, no invertible")
    
    AT = torch.transpose(A,0,1)
    print("Matriz transpuesta =\n", AT )
    AM=torch.mm(AT,A)
    print("Matriz multiplicada por su transpuesta =\n", AM )
    AMP = torch.pinverse(AM)
    print("Matriz pseudoinversa de la anterior =\n", AMP )
    left = torch.mm(AMP,AT)
    print ("Left side of the equation =\n",left)
    right = torch.pinverse(A) 
    print ("Right side of the equation =\n",right)
    
    #compare matriz 
    esIgual = torch.allclose( left, right,  atol=0.1)
    
    print("¿Igual la ecuacion de la propiedad 2?", esIgual)
    return esIgual



#pseudo inversa de una matriz singular.  

print("========================================")
print("Pseudo inversa de invertible")
print("A matrix")
A = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [0 , 2. , 2., 0 , 0 ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [0 , 1. , 0, 4. ,0 ],
                   [1. , 0 , 2., 0 , 6. ]])

testPInversaPropiedad2(A)

print("========================================")
print("Pseudo inversa de no invertible")
print("B matrix")

B = torch.tensor([ [1. , 2. ], [3. , 4. ] , [5. , 6.] ] )

testPInversaPropiedad2(C)


Pseudo inversa de invertible
A matrix
Matriz inicial
tensor([[1., 2., 3., 4., 5.],
        [0., 2., 2., 0., 0.],
        [1., 0., 3., 0., 0.],
        [0., 1., 0., 4., 0.],
        [1., 0., 2., 0., 6.]])
Éxito en la inversa
Matriz transpuesta =
 tensor([[1., 0., 1., 0., 1.],
        [2., 2., 0., 1., 0.],
        [3., 2., 3., 0., 2.],
        [4., 0., 0., 4., 0.],
        [5., 0., 0., 0., 6.]])
Matriz multiplicada por su transpuesta =
 tensor([[ 3.,  2.,  8.,  4., 11.],
        [ 2.,  9., 10., 12., 10.],
        [ 8., 10., 26., 12., 27.],
        [ 4., 12., 12., 32., 20.],
        [11., 10., 27., 20., 61.]])
Matriz pseudoinversa de la anterior =
 tensor([[ 958.7859,  315.7592, -320.2628,  -83.4435,  -55.5455],
        [ 315.7589,  104.3354, -105.5866,  -27.5851,  -18.2650],
        [-320.2625, -105.5866,  107.0878,   27.8979,   18.5152],
        [ -83.4435,  -27.5851,   27.8979,    7.3341,    4.8165],
        [ -55.5455,  -18.2650,   18.5152,    4.8165,    3.2526]])
Left side of the equ

True

**Pregunta 4 (10 puntos, 5 puntos cada ejercicio)**

Sea $A\in\mathbb{R}^{n\times n}$, realice lo siguiente:

---

**Pregunta 4.1**

Defina la función es_simetrica_o_antisimetrica que reciba una matriz, verifique si esta es cuadrada y despliegue un mensaje indicando si la matriz es simétrica, antisimétrica o ninguna de las anteriores. 

**Pregunta 4.2**

Utilizando la función es_simetrica_o_antisimetrica demuestre que la matriz resultante de la operación $A+A^{T}$ es simétrica y la matriz $A-A^{T}$ es anti-simétrica.


In [74]:
#-----------------------------------------------------------------------
#Pregunta 4.1: Verifica si matriz es simetrica o antisimetrica o ninguna
#-----------------------------------------------------------------------

# Bibliotecas
import torch as torch


def es_simetrica_o_antisimetrica(A):
    """
    Verifica si una matriz es simétrica, antisimetrica o ninguna de las anteriores
    Parámetros:
       A: matriz      
    Retorna: sin retorno
    """
    print("============================================")
    print("Matriz inicial")
    print( A )
    
    if (A.shape[0] == A.shape[1]):
        print("La Matriz es cuadrada")
    else:
        print("La Matriz no es cuadrada")
        return
    
    print("Transpuesta de matriz inicial")
    T = torch.transpose(A,0,1)
    print( T )
    
    if torch.equal( A, T):
        print ("Matriz es simetrica")
    elif torch.equal( A, -T):    
        print ("Matriz es antisimetrica")
    else:
        print ("Matriz no es antisimetrica ni simetrica")


A = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [0 , 2. , 2., 0 , 0 ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [0 , 1. , 0, 4. ,0 ],
                   [1. , 0 , 2., 0 , 6. ]])

es_simetrica_o_antisimetrica(A)

B = torch.tensor([ [1. , 2. , 3. , 4. ], 
                   [0 , 2. , 2., 0  ], 
                   [1. , 0 , 3., 0  ],
                   [0 , 1. , 0, 4. ],
                   [1. , 0 , 2., 0  ]])

es_simetrica_o_antisimetrica(B)

C =  torch.tensor([ [0 , -5. ], [5., 0]])

es_simetrica_o_antisimetrica(C)

D =  torch.tensor([ [0 , 1 ], [1, 0]])

es_simetrica_o_antisimetrica(D)

Matriz inicial
tensor([[1., 2., 3., 4., 5.],
        [0., 2., 2., 0., 0.],
        [1., 0., 3., 0., 0.],
        [0., 1., 0., 4., 0.],
        [1., 0., 2., 0., 6.]])
La Matriz es cuadrada
Transpuesta de matriz inicial
tensor([[1., 0., 1., 0., 1.],
        [2., 2., 0., 1., 0.],
        [3., 2., 3., 0., 2.],
        [4., 0., 0., 4., 0.],
        [5., 0., 0., 0., 6.]])
Matriz no es antisimetrica ni simetrica
Matriz inicial
tensor([[1., 2., 3., 4.],
        [0., 2., 2., 0.],
        [1., 0., 3., 0.],
        [0., 1., 0., 4.],
        [1., 0., 2., 0.]])
La Matriz no es cuadrada
Matriz inicial
tensor([[ 0., -5.],
        [ 5.,  0.]])
La Matriz es cuadrada
Transpuesta de matriz inicial
tensor([[ 0.,  5.],
        [-5.,  0.]])
Matriz es antisimetrica
Matriz inicial
tensor([[0, 1],
        [1, 0]])
La Matriz es cuadrada
Transpuesta de matriz inicial
tensor([[0, 1],
        [1, 0]])
Matriz es simetrica


In [75]:
#--------------------------
#Pregunta 1.2: 
#--------------------------

# Bibliotecas
import torch as torch


def es_simetrica_o_antisimetrica(A):
    """
    Verifica si una matriz es simétrica, antisimetrica o ninguna de las anteriores
    Parámetros:
       A: matriz      
    Retorna: sin retorno
    """
    print("============================================")
    print("Matriz inicial")
    print( A )
    
    if (A.shape[0] == A.shape[1]):
        print("La Matriz es cuadrada")
    else:
        print("La Matriz no es cuadrada")
        return
    
    print("Transpuesta de matriz inicial")
    T = torch.transpose(A,0,1)
    print( T )
    
    if torch.equal( A, T):
        print ("Matriz es simetrica")
    elif torch.equal( A, -T):    
        print ("Matriz es antisimetrica")
    else:
        print ("Matriz no es antisimetrica ni simetrica")


A = torch.tensor([ [1. , 2. , 3. , 4. , 5.], 
                   [0 , 2. , 2., 0 , 0 ], 
                   [1. , 0 , 3., 0 ,0 ],
                   [0 , 1. , 0, 4. ,0 ],
                   [1. , 0 , 2., 0 , 6. ]])

es_simetrica_o_antisimetrica(A+torch.transpose(A,0,1))

es_simetrica_o_antisimetrica(A-torch.transpose(A,0,1))

Matriz inicial
tensor([[ 2.,  2.,  4.,  4.,  6.],
        [ 2.,  4.,  2.,  1.,  0.],
        [ 4.,  2.,  6.,  0.,  2.],
        [ 4.,  1.,  0.,  8.,  0.],
        [ 6.,  0.,  2.,  0., 12.]])
La Matriz es cuadrada
Transpuesta de matriz inicial
tensor([[ 2.,  2.,  4.,  4.,  6.],
        [ 2.,  4.,  2.,  1.,  0.],
        [ 4.,  2.,  6.,  0.,  2.],
        [ 4.,  1.,  0.,  8.,  0.],
        [ 6.,  0.,  2.,  0., 12.]])
Matriz es simetrica
Matriz inicial
tensor([[ 0.,  2.,  2.,  4.,  4.],
        [-2.,  0.,  2., -1.,  0.],
        [-2., -2.,  0.,  0., -2.],
        [-4.,  1.,  0.,  0.,  0.],
        [-4.,  0.,  2.,  0.,  0.]])
La Matriz es cuadrada
Transpuesta de matriz inicial
tensor([[ 0., -2., -2., -4., -4.],
        [ 2.,  0., -2.,  1.,  0.],
        [ 2.,  2.,  0.,  0.,  2.],
        [ 4., -1.,  0.,  0.,  0.],
        [ 4.,  0., -2.,  0.,  0.]])
Matriz es antisimetrica
